package com.ethan.gapclient.dal.model;

public class UserLoginInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.login_id
     *
     * @mbggenerated Sat Jan 20 20:18:44 CST 2018
     */
    private Integer loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.account_type
     *
     * @mbggenerated Sat Jan 20 20:18:44 CST 2018
     */
    private String accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.account_id
     *
     * @mbggenerated Sat Jan 20 20:18:44 CST 2018
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.account_password
     *
     * @mbggenerated Sat Jan 20 20:18:44 CST 2018
     */
    private String accountPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.user_id
     *
     * @mbggenerated Sat Jan 20 20:18:44 CST 2018
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.login_id
     *
     * @return the value of user_login_info.login_id
     *
     * @mbggenerated Sat Jan 20 20:18:44 CST 2018
     */
    public Integer getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.login_id
     *
     * @param loginId the value for user_login_info.login_id
     *
     * @mbggenerated Sat Jan 20 20:18:44 CST 2018
     */
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.account_type
     *
     * @return the value of user_login_info.account_type
     *
     * @mbggenerated Sat Jan 20 20:18:44 CST 2018
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.account_type
     *
     * @param accountType the value for user_login_info.account_type
     *
     * @mbggenerated Sat Jan 20 20:18:44 CST 2018
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType == null ? null : accountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.account_id
     *
     * @return the value of user_login_info.account_id
     *
     * @mbggenerated Sat Jan 20 20:18:44 CST 2018
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.account_id
     *
     * @param accountId the value for user_login_info.account_id
     *
     * @mbggenerated Sat Jan 20 20:18:44 CST 2018
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.account_password
     *
     * @return the value of user_login_info.account_password
     *
     * @mbggenerated Sat Jan 20 20:18:44 CST 2018
     */
    public String getAccountPassword() {
        return accountPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.account_password
     *
     * @param accountPassword the value for user_login_info.account_password
     *
     * @mbggenerated Sat Jan 20 20:18:44 CST 2018
     */
    public void setAccountPassword(String accountPassword) {
        this.accountPassword = accountPassword == null ? null : accountPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.user_id
     *
     * @return the value of user_login_info.user_id
     *
     * @mbggenerated Sat Jan 20 20:18:44 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.user_id
     *
     * @param userId the value for user_login_info.user_id
     *
     * @mbggenerated Sat Jan 20 20:18:44 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}